### ISSUE TITLE
How to run the demo with my own dataset? 

### ISSUE THREAD

**Issue by aalzooke** [rui1996/DeRaindrop#1]
Can you please explain how to run this demo using my own dataset? 
Thank you

**Comment by rui1996** [comment]
Replace the '--input_dir ./demo/input/' with --input_dir your_own_data_path

**Comment by rui1996** [comment]
You can find the implementation of attentive-recurrent network and contextual encoder-decoder in generator.py. I combine them together.

**Comment by fairynn** [comment]
Got it. Thanks.
