### ISSUE TITLE
Can this demo used for real time video ? 

### ISSUE THREAD

**Issue by aalzooke** [rui1996/DeRaindrop#2]
I was reading about this project and I noticed it's only for a single image. so is it possible this can be done in real time? 
Thank you for your help.

**Comment by rui1996** [comment]
You can test the code on your GPU and if you find the forwarding time for a single frame of the video is   less than 1/24 second or 1/30 second, it may be suitable for real time.

**Comment by aalzooke** [comment]
Thank you for your quick response, I'm planning to use dash camera in the car where I can remove the Raindrop in real time. Do you think this can be done?
