### ISSUE TITLE
the discriminator is not the discriminator described in your CVPR paper.

### ISSUE THREAD

**Issue by winwinJJiang** [rui1996/DeRaindrop#9]
Is there something wrong???

Or on purpose

**Comment by Ir1d** [comment]
which part is different?

**Comment by winwinJJiang** [comment]
文章里和这里的代码不一样 难道我找错论文了

**Comment by Ir1d** [comment]
https://github.com/rui1996/DeRaindrop/blob/master/models/discriminator.py

**Comment by winwinJJiang** [comment]
x = self.conv6(x)
        mask = self.conv_mask(x)
        x = self.conv7(x * mask)

**Comment by rui1996** [comment]
As stated in the paper, “We extract the features from the last third convolution layers
and multiply back in element-wise.” Why do you think it is wrong?
